### ISSUE TITLE
Why amalgamation support

### ISSUE THREAD

**Issue by boris-kolpackov** [lyrahgames/build2-miniz#1]
I am reviewing the submitted 3.0.2 package and I see quite an elaborate header/source amalgamation machinery that is even enabled by default. I couldn't find any rationale for why it's there, what are the benefits, why it needs to be configurable, etc. Also I've notice that `PACKAGE-README.md` incorrectly states that this package doesn't have any configuration. 

Looking at the upstream, it seems the amalgamation support is there to give people the ability to just drop-in two files into their project and it seems to imply that if one uses a real build system/package manager, then amalgamation is not necessary. Or am I missing something?

**Comment by lyrahgames** [comment]
> I am reviewing the submitted 3.0.2 package and I see quite an elaborate header/source amalgamation machinery that is even enabled by default. I couldn't find any rationale for why it's there, what are the benefits, why it needs to be configurable, etc.

First, I started without amalgamation support to only render the basic functionality.
But the actual CMake files for `miniz` provided it and I wanted to learn how to port this functionality (at least it couldn't hurt to have this). To properly test the amalgamation, I made it configurable.
As `miniz` is released and advertised as a single-header-and-single-source library, I also made it the default behavior.
I thought that installing separate header files would either clutter the main `include` directory or would result in a non-standard subfolder `include/miniz/` or `include/libminiz/`.
Furthermore, concerning the `dist` command, it would be inconsistent to provide a package which then uses multiple headers and multiples source as opposed to its actual releases.

> Also I've notice that `PACKAGE-README.md` incorrectly states that this package doesn't have any configuration.

That was an unintentional mistake and I will fix that. Thanks for noticing.

> Looking at the upstream, it seems the amalgamation support is there to give people the ability to just drop-in two files into their project and it seems to imply that if one uses a real build system/package manager, then amalgamation is not necessary. Or am I missing something?

Indeed, in a certain sense, it is not necessary. I did not want to deviate too much from the original repository and its build system.

**Comment by boris-kolpackov** [comment]
I understand your reasoning. I also appreciate the desire to try a new mechanism that can cleanly solve an interesting problem. In particular:

> I thought that installing separate header files would either clutter the main include directory or would result in a non-standard subfolder `include/miniz/` or `include/libminiz/`.

This would have been a strong argument in favor of the amalgamation if the non-amalgamated headers could clash with other libraries. But, thankfully, all the non-amalgamated headers are prefixed with `miniz_` so this is not an issue.

Regarding not deviating from upstream, this is a good idea but only to a degree. When we see upstream doing something strange, we should always try to understand why they are doing this and whether it still makes sense in our context. My understanding is that upstream doing amalgamation is to support projects that don't have access to a proper build system/package manager. This is not an issue in our case.

Now we come to the costs. From your reply I believe you think there aren't any or they are negligible. But they are not. Any variability adds complexity. Let me list the costs that I can think of just off the top of my head:

1. Greater chance to have bugs. Forgetting to list configuration variables in `PACKAGE-README.md` is a case in point: if there were no configuration variables, there would be nothing to forget.

2. The user of this package will now need to stop and understand what these configuration variables mean and what is most appropriate for their use case.

3. Following from 3, if two users make different (potentially misguided) decisions, then their packages may not be usable together.

4. There is extra CI time spent on testing various configurations.

5. There is extra time spent by me when reviewing this package. Instead of quickly skimming over a pretty standard C library build, I now have to spend a considerable time understanding what's going on, is the behavior correct in all cases, are there any bugs, etc.

So we incur all of these costs for, as far as I can see, exactly 0 benefit in our context. I think we should drop the amalgamation support entirely and make it a simple C library with a static set of headers and sources.

Sorry if I sound too negative, but lately I've been spending more and more of my time reviewing packages and I don't find it very enjoyable, mostly because upstream C/C++ projects are usually a big mess that often sills over into `buildfiles`.

**Comment by lyrahgames** [comment]
> Now we come to the costs. From your reply I believe you think there aren't any or they are negligible. But they are not. Any variability adds complexity.
> ...
> So we incur all of these costs for, as far as I can see, exactly 0 benefit in our context. I think we should drop the amalgamation support entirely and make it a simple C library with a static set of headers and sources.

Indeed, I only had the best things in mind and did not want to deliberately make the package more complex than necessary. For me, it was easier to add the amalgamation support now before (maybe months or years later) me, someone else, or updates of the upstream project would require me to add it anyway reading through the upstream build system, again. But I see all your points and I have no problems with dropping the amalgamation support. It would still be part of the commit tree and if we need it we can add it again.

> Sorry if I sound too negative, but lately I've been spending more and more of my time reviewing packages and I don't find it very enjoyable, mostly because upstream C/C++ projects are usually a big mess that often sills over into `buildfiles`.

I am sorry to hear that and I see, that I am not entirely innocent of this as I published a few packages that required your review. I do not believe it to be enjoyable and I also do not want take up too much of your time.
But FYI: I really much appreciate your review as it is very helpful and makes me understand the features and aspects of `build2` in a way that its manual is not able to. I try to give my best packaging third-party projects. For any further suggestions from your side on how I could make reviews easier or help in general, please, do not hesitate to send me an e-mail.

**Comment by boris-kolpackov** [comment]
> For me, it was easier to add the amalgamation support now before (maybe months or years later) me, someone else, or updates of the upstream project would require me to add it anyway reading through the upstream build system, again.

Yes, that's a valid concern. The way I would address it is by adding a note to the `buildfile` explaining that the amalgamation support was considered but deemed not to be necessary. And perhaps include a reference to this issue.

> But I see all your points and I have no problems with dropping the amalgamation support.

Perfect, thanks! I've dropped the submitted package from the queue so you are good to resubmit when ready.

> I try to give my best packaging third-party projects.

Yes, and I've noted and appreciate that! In fact, I tend to give more feedback to people who strive to produce quality work, so don't view my comments as criticism of the quality of your work but rather as me appreciating your effort and trying to provide further insight.

**Comment by lyrahgames** [comment]
I have removed the amalgamation support in the latest commit. [Here](https://ci.cppget.org/@5769e347-9fbc-4cc3-baad-3b2c2903fe47), you can find the CI run.
Everything should be back to normal ;)

> Yes, that's a valid concern. The way I would address it is by adding a note to the `buildfile` explaining that the amalgamation support was considered but deemed not to be necessary. And perhaps include a reference to this issue.

I added this note to the `README.md` and not the `buildfile`. However, the note refers to this issue.
Hope that is also ok.

> Perfect, thanks! I've dropped the submitted package from the queue so you are good to resubmit when ready.

Nice. I will resubmit the package as soon as you would consider this issue closed.
Otherwise, I can still try to adjust some things.

> Yes, and I've noted and appreciate that! In fact, I tend to give more feedback to people who strive to produce quality work, so don't view my comments as criticism of the quality of your work but rather as me appreciating your effort and trying to provide further insight.

I do not view your comments as any kind of criticism. As I said, I totally appreciate them, because they are very helpful, but I also want to make sure that my package submissions are not getting on anyone's nerves ^^ So, thank you very much! I really want to learn more!

**Comment by boris-kolpackov** [comment]
> I will resubmit the package as soon as you would consider this issue closed.

Can I ask you going forward to just close the issue and re-submit the package when you deem it fixed. The reason is that these days I don't have the bandwidth to review individual changes in the packages (or there is a long delay before I can get to them). So I would prefer to just review the final submitted package (which will also get some extra testing in queue.cppget.org). Thanks!

**Comment by lyrahgames** [comment]
Yes, of course. I will do that in the future!
